FROM openjdk:8-jdk-alpine

# Maven build finalName
ARG JAR_FILE=target/bookstore-0.0.1-SNAPSHOT.jar

# cd /opt/app
WORKDIR /opt/app

COPY ${JAR_FILE} bookstore.jar

ENTRYPOINT ["java","-jar", "bookstore.jar"]
